### ISSUE TITLE
Wait for Issue4899 fixed

### ISSUE THREAD

**Issue by chai2010** [chai2010/assert#1]
https://code.google.com/p/go/issues/detail?id=4899

**Comment by achun** [comment]
柴大, 这个问题我没法完全明白连接中的讨论.  我理解和遇到的问题是:
testing 包无法支持调用所引发的层级关系, 造成输出结果无法对应期望的源代码行信息.

我有个想法, 给 testing 做个接口, 这个接口和 testing.T/B 完全一致, 因为接口和 struct 的类型不同, 如果做特殊处理, runtime 是不是能识别 类型的区别去自动识别 caller level  呢?
意思是: 应用通过在合适的地方使用接口或者 *struct , 使 runtime 做到自动化修正 level 的的值, 输出期望的错误所在的位置信息.

**Comment by chai2010** [comment]
主要问题是, `testing` 输出时都是通过 `testing.T.log` 的内部函数完成,
而这个函数的 `level` 是写死的(只能输出 `testing.T.PublicFunc` 被调用的位置).

回复中有人给出了一个临时方案:
https://code.google.com/p/go/issues/detail?id=4899#c3

大概是基于 `\b` 来删除 `testing.T.log` 多输出的头信息.
但是我感觉会导致输出信息很复杂(特别是给其他程序处理时).

我前几天提多一个方案, 是增加一个 `testing.T.Print` 函数.
`testing.T.Print` 输出原始信息, 不增加任何头信息 (caller信息由包装者自己添加).
https://code.google.com/p/go/issues/detail?id=8783

目前讨论中, 好像倾向于增加一个 `Up` 函数, 来调整 level .
我觉得这也是一种解决方式.

自动化修正 level, 不清楚是否能够做到.
如果能做到, 目前也算是比较不错的一个解决方案了.

**Comment by chai2010** [comment]
Go1.9+ 增加了 `tb.Helper` 函数:
https://godoc.org/testing#B.Helper
